# https://taskfile.dev
# Git Merge Editor - Taskfile Configuration
# Généré avec Copier depuis taskfile-starter template
#
# USAGE:
#   task          # Menu principal
#   task check    # Vérifier les prérequis
#   task --list   # Lister toutes les tâches

version: '3'

# ============================================================================
# VARIABLES GLOBALES
# ============================================================================
vars:
  # === PROJET ===
  PROJECT_NAME: "VibeMerge"
  PROJECT_VERSION: "0.1.0"
  DOMAIN: "git-merge-editor.local"

  # === UI STYLING ===
  UI_WIDTH: "70"

  UI_COLOR_PRIMARY: "212"           # Rose/magenta
  UI_COLOR_INFO: "51"               # Cyan
  UI_COLOR_ACCENT: "99"             # Violet

  UI_COLOR_SUCCESS: "42"            # Vert
  UI_COLOR_ERROR: "196"             # Rouge
  UI_COLOR_WARNING: "226"           # Jaune
  UI_COLOR_MUTED: "240"             # Gris discret

  # === COMPORTEMENT ===
  ASK_CONFIRMATION: true

  # === GIT ===
  GIT_COMMIT:
    sh: git log -n 1 --format=%h 2>/dev/null || echo "no-git"
  GIT_BRANCH:
    sh: git branch --show-current 2>/dev/null || echo "no-branch"


# ============================================================================
# INCLUDES - Modules du framework
# ============================================================================
includes:
  # Core (internal - composants de base)
  ui:
    taskfile: ./taskfiles/ui.yml
    internal: true
  utils:
    taskfile: ./taskfiles/utils.yml
    internal: true


  # AI - Outils IA (toujours inclus)
  ai:
    taskfile: ./taskfiles/ai.yml








  # Ajouter vos modules ici:
  # mymodule:
  #   taskfile: ./taskfiles/modules/mymodule.yml

# ============================================================================
# CONFIGURATION
# ============================================================================
silent: true

# ============================================================================
# TACHES PRINCIPALES
# ============================================================================
tasks:
  default:
    desc: "Affiche l'aide et liste les tâches"
    cmds:
      - clear
      - task: ui:banner
        vars:
          TITLE: "{{.PROJECT_NAME}}"
          SUBTITLE: "v{{.PROJECT_VERSION}} | {{.GIT_BRANCH}}@{{.GIT_COMMIT}}"
          COLOR: "{{.UI_COLOR_PRIMARY}}"
      - task: ui:spacer
      - task: _menu-main
      - task: ui:spacer
      - task: _menu-modules
      - task: _menu-footer

  _menu-main:
    internal: true
    cmds:
      - task: ui:menu-box
        vars:
          ICON: ""
          TITLE: "Commandes principales"
          COLOR: "{{.UI_COLOR_INFO}}"
          ITEMS:
            - {cmd: check, label: Prérequis, hint: "vérifier les outils"}
            - {cmd: info, label: Informations, hint: "détails du projet"}

            - {cmd: help, label: Aide, hint: "documentation"}
  _menu-modules:
    internal: true
    cmds:
      - task: ui:menu-box
        vars:
          ICON: ""
          TITLE: "Modules"
          COLOR: "{{.UI_COLOR_ACCENT}}"
          ITEMS:
            - {cmd: ai, label: AI Tools, hint: "commit, PR, branch"}









  _menu-footer:
    internal: true
    cmds:
      - task: ui:spacer
      - task: ui:muted
        vars: {TEXT: "  task <cmd> pour exécuter  |  task --list pour tout voir"}

  # --------------------------------------------------------------------------
  # VERIFICATION
  # --------------------------------------------------------------------------
  check:
    desc: "Vérifier les prérequis système"
    aliases: [requirements, prereq]
    cmds:
      - task: ui:header
        vars: {TITLE: "VÉRIFICATION DES PRÉREQUIS", COLOR: "{{.UI_COLOR_INFO}}"}
      - task: ui:spacer
      - task: ui:section
        vars: {TITLE: "Outils requis:"}
      - task: ui:check-cmd
        vars: {CMD: "gum", NAME: "Gum"}
      - task: ui:check-cmd
        vars: {CMD: "jq", NAME: "jq"}
      - task: ui:check-cmd
        vars: {CMD: "curl", NAME: "curl"}
      - task: ui:check-cmd
        vars: {CMD: "git", NAME: "Git"}
      - task: ui:spacer
      - task: ui:section
        vars: {TITLE: "Outils optionnels:"}
      - task: ui:check-cmd-optional
        vars: {CMD: "docker", NAME: "Docker"}

      - task: ui:check-cmd-optional
        vars: {CMD: "ollama", NAME: "Ollama"}
      - task: ui:check-cmd-optional
        vars: {CMD: "gh", NAME: "GitHub CLI"}



      - task: ui:spacer
      - task: ui:success
        vars: {TEXT: "Vérification terminée!"}

  # --------------------------------------------------------------------------
  # INFORMATION
  # --------------------------------------------------------------------------
  info:
    desc: "Afficher les informations du projet"
    cmds:
      - task: ui:header
        vars: {TITLE: "INFORMATIONS", COLOR: "{{.UI_COLOR_INFO}}"}
      - task: ui:spacer
      - task: ui:var-box
        vars:
          ICON: ""
          TITLE: "Projet"
          COLOR: "{{.UI_COLOR_PRIMARY}}"
          VARS:
            - {key: "Nom", value: "{{.PROJECT_NAME}}"}
            - {key: "Version", value: "{{.PROJECT_VERSION}}"}
            - {key: "Branche", value: "{{.GIT_BRANCH}}"}
            - {key: "Commit", value: "{{.GIT_COMMIT}}"}



  # --------------------------------------------------------------------------
  # AIDE
  # --------------------------------------------------------------------------
  help:
    desc: "Aide détaillée"
    cmds:
      - task: ui:header
        vars: {TITLE: "AIDE - {{.PROJECT_NAME}}", COLOR: "{{.UI_COLOR_PRIMARY}}"}
      - task: ui:spacer
      - task: ui:menu-box
        vars:
          ICON: ""
          TITLE: "Commandes principales"
          COLOR: "{{.UI_COLOR_INFO}}"
          ITEMS:
            - {cmd: check, label: "Prérequis", hint: "vérifier les outils requis"}
            - {cmd: info, label: "Informations", hint: "détails du projet"}

      - task: ui:spacer
      - task: ui:menu-box
        vars:
          ICON: ""
          TITLE: "Outils IA"
          COLOR: "{{.UI_COLOR_ACCENT}}"
          ITEMS:
            - {cmd: "ai:commit:yolo", label: "Commit YOLO", hint: "auto add+commit+push"}
            - {cmd: "ai:pr", label: "Create PR", hint: "PR avec description IA"}
            - {cmd: "ai:branch -- nom", label: "Branch", hint: "créer branche conventionnelle"}
            - {cmd: "ai:merge", label: "Merge PR", hint: "merger une PR"}







      - task: ui:spacer
      - task: ui:menu-box
        vars:
          ICON: ""
          TITLE: "Utilitaires"
          COLOR: "{{.UI_COLOR_MUTED}}"
          ITEMS:
            - {cmd: "utils:clean", label: "Clean", hint: "nettoyer fichiers générés"}
            - {cmd: "utils:clean-docker", label: "Clean Docker", hint: "pruner Docker"}
      - task: ui:spacer
      - task: ui:muted
        vars: {TEXT: "  Documentation: task --list pour voir toutes les tâches"}

  # --------------------------------------------------------------------------
  # SHOWCASE UI
  # --------------------------------------------------------------------------
  showcase:
    desc: "Afficher tous les composants UI disponibles"
    cmds:
      - task: ui:showcase

  # --------------------------------------------------------------------------
  # TEMPLATE UPDATE
  # --------------------------------------------------------------------------
  template:update:
    desc: "Mettre a jour depuis le template Copier (usage: task template:update [-- v1.0.0])"
    cmds:
      - |
        # Vérifier copier
        if ! command -v copier &>/dev/null; then
          gum style --foreground 196 " Copier non installé (pip install copier)"
          exit 1
        fi

        # Vérifier .copier-answers.yml
        if [ ! -f ".copier-answers.yml" ]; then
          gum style --foreground 196 " Fichier .copier-answers.yml non trouvé"
          gum style --foreground 240 "   Ce projet n'a pas été généré avec Copier"
          exit 1
        fi

        # Vérifier git clean
        if [ -n "$(git status --porcelain)" ]; then
          gum style --foreground 226 "  Changements non commités détectés"
          echo ""
          git status --short
          echo ""
          if ! gum confirm "Continuer quand même? (non recommandé)"; then
            gum style --foreground 240 " Commitez vos changements d'abord"
            exit 1
          fi
        fi

        # Extraire infos du template
        CURRENT_COMMIT=$(grep "^_commit:" .copier-answers.yml | awk '{print $2}' | tr -d '"')
        SRC_PATH=$(grep "^_src_path:" .copier-answers.yml | awk '{print $2}' | tr -d '"')
        TARGET_REF="{{.CLI_ARGS | default ""}}"

        gum style --foreground 212 "Mise à jour du template"
        echo ""
        gum style --foreground 240 "Source: $SRC_PATH"
        gum style --foreground 240 "Commit actuel: $CURRENT_COMMIT"

        # Avertir si source locale (les tags ne fonctionneront pas)
        if [[ "$SRC_PATH" == /* ]] || [[ "$SRC_PATH" == ~* ]]; then
          echo ""
          gum style --foreground 226 "  Source locale détectée!"
          gum style --foreground 240 "   Les tags ne fonctionnent qu'avec une URL Git."
          gum style --foreground 240 "   Pour corriger: task template:recopy -- URL_GIT"
          echo ""
        fi

        # Si pas de ref spécifiée, proposer les options
        if [ -z "$TARGET_REF" ]; then
          TARGET_REF=$(gum choose \
            --cursor.foreground="212" \
            --header="Version cible:" \
            "HEAD (dernier commit)" \
            "Dernier tag" \
            "Saisir manuellement")

          case "$TARGET_REF" in
            *HEAD*) TARGET_REF="HEAD" ;;
            *tag*)
              # Récupérer le dernier tag du remote
              LATEST_TAG=$(git ls-remote --tags "$SRC_PATH" 2>/dev/null | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1)
              if [ -n "$LATEST_TAG" ]; then
                TARGET_REF="$LATEST_TAG"
                gum style --foreground 42 "Dernier tag: $LATEST_TAG"
              else
                gum style --foreground 226 "  Aucun tag trouvé, utilisation de HEAD"
                TARGET_REF="HEAD"
              fi
              ;;
            *manuellement*)
              TARGET_REF=$(gum input --placeholder "v1.0.0 ou HEAD" --prompt "Ref: ")
              [ -z "$TARGET_REF" ] && TARGET_REF="HEAD"
              ;;
          esac
        fi

        gum style --foreground 51 "Cible: $TARGET_REF"
        echo ""

        gum style --foreground 212 "Mise à jour en cours..."
        echo ""

        # Copier update avec les bonnes options
        if copier update --vcs-ref "$TARGET_REF" --skip-answered --conflict rej --trust; then
          echo ""
          gum style --foreground 42 " Mise à jour réussie!"

          # Vérifier s'il y a des fichiers .rej
          REJ_FILES=$(find . -name "*.rej" -type f 2>/dev/null)
          if [ -n "$REJ_FILES" ]; then
            echo ""
            gum style --foreground 226 "  Conflits détectés (fichiers .rej):"
            echo "$REJ_FILES" | while read f; do
              gum style --foreground 240 "   $f"
            done
            gum style --foreground 240 "   Résolvez-les manuellement puis supprimez les .rej"
          fi

        else
          echo ""
          gum style --foreground 196 " Update échoué"
          echo ""
          gum style --foreground 240 "Options:"
          gum style --foreground 240 "  1. task template:update -- HEAD"
          gum style --foreground 240 "  2. task template:recopy (écrase les modifications)"
        fi

  template:recopy:
    desc: "Re-appliquer le template (écrase les modifications locales)"
    cmds:
      - |
        if ! command -v copier &>/dev/null; then
          gum style --foreground 196 " Copier non installé"
          exit 1
        fi

        TARGET_REF="{{.CLI_ARGS | default "HEAD"}}"

        gum style --foreground 196 "  ATTENTION: recopy écrase vos modifications!"
        gum style --foreground 240 "  Cible: $TARGET_REF"
        echo ""

        if gum confirm --default=false "Re-appliquer le template?"; then
          copier recopy --vcs-ref "$TARGET_REF" --skip-answered -f --trust
          echo ""
          gum style --foreground 42 " Template ré-appliqué!"
        else
          gum style --foreground 240 " Annulé"
        fi
